//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MISModel", "FK_StudentInfo_DepartmentInfo", "DepartmentInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StudentInfo.DepartmentInfo), "StudentInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentInfo.StudentInfo), true)]
[assembly: EdmRelationshipAttribute("MISModel", "FK_StudentInfo2_GenderId", "GenderId", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StudentInfo.GenderId), "StudentInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentInfo.StudentInfo), true)]
[assembly: EdmRelationshipAttribute("MISModel", "FK_StudentInfo_SemesterInfo", "SemesterInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StudentInfo.SemesterInfo), "StudentInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentInfo.StudentInfo), true)]
[assembly: EdmRelationshipAttribute("MISModel", "FK_StudentInfo_ShiftInfo", "ShiftInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StudentInfo.ShiftInfo), "StudentInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentInfo.StudentInfo), true)]

#endregion

namespace StudentInfo
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MISEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MISEntities object using the connection string found in the 'MISEntities' section of the application configuration file.
        /// </summary>
        public MISEntities() : base("name=MISEntities", "MISEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MISEntities object.
        /// </summary>
        public MISEntities(string connectionString) : base(connectionString, "MISEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MISEntities object.
        /// </summary>
        public MISEntities(EntityConnection connection) : base(connection, "MISEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DepartmentInfo> DepartmentInfoes
        {
            get
            {
                if ((_DepartmentInfoes == null))
                {
                    _DepartmentInfoes = base.CreateObjectSet<DepartmentInfo>("DepartmentInfoes");
                }
                return _DepartmentInfoes;
            }
        }
        private ObjectSet<DepartmentInfo> _DepartmentInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GenderId> GenderIds
        {
            get
            {
                if ((_GenderIds == null))
                {
                    _GenderIds = base.CreateObjectSet<GenderId>("GenderIds");
                }
                return _GenderIds;
            }
        }
        private ObjectSet<GenderId> _GenderIds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoginInfo> LoginInfoes
        {
            get
            {
                if ((_LoginInfoes == null))
                {
                    _LoginInfoes = base.CreateObjectSet<LoginInfo>("LoginInfoes");
                }
                return _LoginInfoes;
            }
        }
        private ObjectSet<LoginInfo> _LoginInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SemesterInfo> SemesterInfoes
        {
            get
            {
                if ((_SemesterInfoes == null))
                {
                    _SemesterInfoes = base.CreateObjectSet<SemesterInfo>("SemesterInfoes");
                }
                return _SemesterInfoes;
            }
        }
        private ObjectSet<SemesterInfo> _SemesterInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ShiftInfo> ShiftInfoes
        {
            get
            {
                if ((_ShiftInfoes == null))
                {
                    _ShiftInfoes = base.CreateObjectSet<ShiftInfo>("ShiftInfoes");
                }
                return _ShiftInfoes;
            }
        }
        private ObjectSet<ShiftInfo> _ShiftInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StudentInfo> StudentInfoes
        {
            get
            {
                if ((_StudentInfoes == null))
                {
                    _StudentInfoes = base.CreateObjectSet<StudentInfo>("StudentInfoes");
                }
                return _StudentInfoes;
            }
        }
        private ObjectSet<StudentInfo> _StudentInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DepartmentInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDepartmentInfoes(DepartmentInfo departmentInfo)
        {
            base.AddObject("DepartmentInfoes", departmentInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GenderIds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGenderIds(GenderId genderId)
        {
            base.AddObject("GenderIds", genderId);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoginInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoginInfoes(LoginInfo loginInfo)
        {
            base.AddObject("LoginInfoes", loginInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SemesterInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSemesterInfoes(SemesterInfo semesterInfo)
        {
            base.AddObject("SemesterInfoes", semesterInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ShiftInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShiftInfoes(ShiftInfo shiftInfo)
        {
            base.AddObject("ShiftInfoes", shiftInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StudentInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudentInfoes(StudentInfo studentInfo)
        {
            base.AddObject("StudentInfoes", studentInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<SP_GRIDVIEWDISPLAY_Result> SP_GRIDVIEWDISPLAY()
        {
            return base.ExecuteFunction<SP_GRIDVIEWDISPLAY_Result>("SP_GRIDVIEWDISPLAY");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<SP_GRIDVIEWDISPLAYS_Result> SP_GRIDVIEWDISPLAYS()
        {
            return base.ExecuteFunction<SP_GRIDVIEWDISPLAYS_Result>("SP_GRIDVIEWDISPLAYS");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="stdId">No Metadata Documentation available.</param>
        /// <param name="did">No Metadata Documentation available.</param>
        public ObjectResult<SP_DepartmentWiseStudentinfo_Result> SP_DepartmentWiseStudentinfo(Nullable<global::System.Int32> stdId, Nullable<global::System.Int32> did)
        {
            ObjectParameter stdIdParameter;
            if (stdId.HasValue)
            {
                stdIdParameter = new ObjectParameter("StdId", stdId);
            }
            else
            {
                stdIdParameter = new ObjectParameter("StdId", typeof(global::System.Int32));
            }
    
            ObjectParameter didParameter;
            if (did.HasValue)
            {
                didParameter = new ObjectParameter("Did", did);
            }
            else
            {
                didParameter = new ObjectParameter("Did", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<SP_DepartmentWiseStudentinfo_Result>("SP_DepartmentWiseStudentinfo", stdIdParameter, didParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MISModel", Name="DepartmentInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DepartmentInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DepartmentInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static DepartmentInfo CreateDepartmentInfo(global::System.Int32 id)
        {
            DepartmentInfo departmentInfo = new DepartmentInfo();
            departmentInfo.Id = id;
            return departmentInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MISModel", "FK_StudentInfo_DepartmentInfo", "StudentInfo")]
        public EntityCollection<StudentInfo> StudentInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentInfo>("MISModel.FK_StudentInfo_DepartmentInfo", "StudentInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentInfo>("MISModel.FK_StudentInfo_DepartmentInfo", "StudentInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MISModel", Name="GenderId")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GenderId : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GenderId object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static GenderId CreateGenderId(global::System.Int32 id)
        {
            GenderId genderId = new GenderId();
            genderId.ID = id;
            return genderId;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MISModel", "FK_StudentInfo2_GenderId", "StudentInfo")]
        public EntityCollection<StudentInfo> StudentInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentInfo>("MISModel.FK_StudentInfo2_GenderId", "StudentInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentInfo>("MISModel.FK_StudentInfo2_GenderId", "StudentInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MISModel", Name="LoginInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoginInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoginInfo object.
        /// </summary>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static LoginInfo CreateLoginInfo(global::System.String userName, global::System.String password)
        {
            LoginInfo loginInfo = new LoginInfo();
            loginInfo.UserName = userName;
            loginInfo.Password = password;
            return loginInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MISModel", Name="SemesterInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SemesterInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SemesterInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static SemesterInfo CreateSemesterInfo(global::System.Int32 id)
        {
            SemesterInfo semesterInfo = new SemesterInfo();
            semesterInfo.Id = id;
            return semesterInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Semester
        {
            get
            {
                return _Semester;
            }
            set
            {
                OnSemesterChanging(value);
                ReportPropertyChanging("Semester");
                _Semester = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Semester");
                OnSemesterChanged();
            }
        }
        private global::System.String _Semester;
        partial void OnSemesterChanging(global::System.String value);
        partial void OnSemesterChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MISModel", "FK_StudentInfo_SemesterInfo", "StudentInfo")]
        public EntityCollection<StudentInfo> StudentInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentInfo>("MISModel.FK_StudentInfo_SemesterInfo", "StudentInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentInfo>("MISModel.FK_StudentInfo_SemesterInfo", "StudentInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MISModel", Name="ShiftInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ShiftInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShiftInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static ShiftInfo CreateShiftInfo(global::System.Int32 id)
        {
            ShiftInfo shiftInfo = new ShiftInfo();
            shiftInfo.Id = id;
            return shiftInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiftType
        {
            get
            {
                return _ShiftType;
            }
            set
            {
                OnShiftTypeChanging(value);
                ReportPropertyChanging("ShiftType");
                _ShiftType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiftType");
                OnShiftTypeChanged();
            }
        }
        private global::System.String _ShiftType;
        partial void OnShiftTypeChanging(global::System.String value);
        partial void OnShiftTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MISModel", "FK_StudentInfo_ShiftInfo", "StudentInfo")]
        public EntityCollection<StudentInfo> StudentInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentInfo>("MISModel.FK_StudentInfo_ShiftInfo", "StudentInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentInfo>("MISModel.FK_StudentInfo_ShiftInfo", "StudentInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MISModel", Name="StudentInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StudentInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StudentInfo object.
        /// </summary>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        public static StudentInfo CreateStudentInfo(global::System.Int32 studentId)
        {
            StudentInfo studentInfo = new StudentInfo();
            studentInfo.StudentId = studentId;
            return studentInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                if (_StudentId != value)
                {
                    OnStudentIdChanging(value);
                    ReportPropertyChanging("StudentId");
                    _StudentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StudentId");
                    OnStudentIdChanged();
                }
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SemesterId
        {
            get
            {
                return _SemesterId;
            }
            set
            {
                OnSemesterIdChanging(value);
                ReportPropertyChanging("SemesterId");
                _SemesterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SemesterId");
                OnSemesterIdChanged();
            }
        }
        private Nullable<global::System.Int32> _SemesterId;
        partial void OnSemesterIdChanging(Nullable<global::System.Int32> value);
        partial void OnSemesterIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ShiftId
        {
            get
            {
                return _ShiftId;
            }
            set
            {
                OnShiftIdChanging(value);
                ReportPropertyChanging("ShiftId");
                _ShiftId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShiftId");
                OnShiftIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ShiftId;
        partial void OnShiftIdChanging(Nullable<global::System.Int32> value);
        partial void OnShiftIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GenderId
        {
            get
            {
                return _GenderId;
            }
            set
            {
                OnGenderIdChanging(value);
                ReportPropertyChanging("GenderId");
                _GenderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenderId");
                OnGenderIdChanged();
            }
        }
        private Nullable<global::System.Int32> _GenderId;
        partial void OnGenderIdChanging(Nullable<global::System.Int32> value);
        partial void OnGenderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Contact
        {
            get
            {
                return _Contact;
            }
            set
            {
                OnContactChanging(value);
                ReportPropertyChanging("Contact");
                _Contact = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Contact");
                OnContactChanged();
            }
        }
        private Nullable<global::System.Int32> _Contact;
        partial void OnContactChanging(Nullable<global::System.Int32> value);
        partial void OnContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Session
        {
            get
            {
                return _Session;
            }
            set
            {
                OnSessionChanging(value);
                ReportPropertyChanging("Session");
                _Session = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Session");
                OnSessionChanged();
            }
        }
        private global::System.String _Session;
        partial void OnSessionChanging(global::System.String value);
        partial void OnSessionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateofBirth
        {
            get
            {
                return _DateofBirth;
            }
            set
            {
                OnDateofBirthChanging(value);
                ReportPropertyChanging("DateofBirth");
                _DateofBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateofBirth");
                OnDateofBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateofBirth;
        partial void OnDateofBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateofBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DepId
        {
            get
            {
                return _DepId;
            }
            set
            {
                OnDepIdChanging(value);
                ReportPropertyChanging("DepId");
                _DepId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepId");
                OnDepIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DepId;
        partial void OnDepIdChanging(Nullable<global::System.Int32> value);
        partial void OnDepIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MISModel", "FK_StudentInfo_DepartmentInfo", "DepartmentInfo")]
        public DepartmentInfo DepartmentInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DepartmentInfo>("MISModel.FK_StudentInfo_DepartmentInfo", "DepartmentInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DepartmentInfo>("MISModel.FK_StudentInfo_DepartmentInfo", "DepartmentInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DepartmentInfo> DepartmentInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DepartmentInfo>("MISModel.FK_StudentInfo_DepartmentInfo", "DepartmentInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DepartmentInfo>("MISModel.FK_StudentInfo_DepartmentInfo", "DepartmentInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MISModel", "FK_StudentInfo2_GenderId", "GenderId")]
        public GenderId GenderId1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GenderId>("MISModel.FK_StudentInfo2_GenderId", "GenderId").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GenderId>("MISModel.FK_StudentInfo2_GenderId", "GenderId").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GenderId> GenderId1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GenderId>("MISModel.FK_StudentInfo2_GenderId", "GenderId");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GenderId>("MISModel.FK_StudentInfo2_GenderId", "GenderId", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MISModel", "FK_StudentInfo_SemesterInfo", "SemesterInfo")]
        public SemesterInfo SemesterInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SemesterInfo>("MISModel.FK_StudentInfo_SemesterInfo", "SemesterInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SemesterInfo>("MISModel.FK_StudentInfo_SemesterInfo", "SemesterInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SemesterInfo> SemesterInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SemesterInfo>("MISModel.FK_StudentInfo_SemesterInfo", "SemesterInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SemesterInfo>("MISModel.FK_StudentInfo_SemesterInfo", "SemesterInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MISModel", "FK_StudentInfo_ShiftInfo", "ShiftInfo")]
        public ShiftInfo ShiftInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShiftInfo>("MISModel.FK_StudentInfo_ShiftInfo", "ShiftInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShiftInfo>("MISModel.FK_StudentInfo_ShiftInfo", "ShiftInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ShiftInfo> ShiftInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShiftInfo>("MISModel.FK_StudentInfo_ShiftInfo", "ShiftInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ShiftInfo>("MISModel.FK_StudentInfo_ShiftInfo", "ShiftInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MISModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="MISModel", Name="SP_DepartmentWiseStudentinfo_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_DepartmentWiseStudentinfo_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SP_DepartmentWiseStudentinfo_Result object.
        /// </summary>
        /// <param name="rollNo">Initial value of the RollNo property.</param>
        /// <param name="shift">Initial value of the Shift property.</param>
        public static SP_DepartmentWiseStudentinfo_Result CreateSP_DepartmentWiseStudentinfo_Result(global::System.Int32 rollNo, global::System.String shift)
        {
            SP_DepartmentWiseStudentinfo_Result sP_DepartmentWiseStudentinfo_Result = new SP_DepartmentWiseStudentinfo_Result();
            sP_DepartmentWiseStudentinfo_Result.RollNo = rollNo;
            sP_DepartmentWiseStudentinfo_Result.Shift = shift;
            return sP_DepartmentWiseStudentinfo_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RollNo
        {
            get
            {
                return _RollNo;
            }
            set
            {
                OnRollNoChanging(value);
                ReportPropertyChanging("RollNo");
                _RollNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RollNo");
                OnRollNoChanged();
            }
        }
        private global::System.Int32 _RollNo;
        partial void OnRollNoChanging(global::System.Int32 value);
        partial void OnRollNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Semester
        {
            get
            {
                return _Semester;
            }
            set
            {
                OnSemesterChanging(value);
                ReportPropertyChanging("Semester");
                _Semester = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Semester");
                OnSemesterChanged();
            }
        }
        private global::System.String _Semester;
        partial void OnSemesterChanging(global::System.String value);
        partial void OnSemesterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Shift
        {
            get
            {
                return _Shift;
            }
            set
            {
                OnShiftChanging(value);
                ReportPropertyChanging("Shift");
                _Shift = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Shift");
                OnShiftChanged();
            }
        }
        private global::System.String _Shift;
        partial void OnShiftChanging(global::System.String value);
        partial void OnShiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GendarType
        {
            get
            {
                return _GendarType;
            }
            set
            {
                OnGendarTypeChanging(value);
                ReportPropertyChanging("GendarType");
                _GendarType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GendarType");
                OnGendarTypeChanged();
            }
        }
        private global::System.String _GendarType;
        partial void OnGendarTypeChanging(global::System.String value);
        partial void OnGendarTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="MISModel", Name="SP_GRIDVIEWDISPLAY_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_GRIDVIEWDISPLAY_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SP_GRIDVIEWDISPLAY_Result object.
        /// </summary>
        /// <param name="rollNo">Initial value of the RollNo property.</param>
        /// <param name="shift">Initial value of the Shift property.</param>
        public static SP_GRIDVIEWDISPLAY_Result CreateSP_GRIDVIEWDISPLAY_Result(global::System.Int32 rollNo, global::System.String shift)
        {
            SP_GRIDVIEWDISPLAY_Result sP_GRIDVIEWDISPLAY_Result = new SP_GRIDVIEWDISPLAY_Result();
            sP_GRIDVIEWDISPLAY_Result.RollNo = rollNo;
            sP_GRIDVIEWDISPLAY_Result.Shift = shift;
            return sP_GRIDVIEWDISPLAY_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RollNo
        {
            get
            {
                return _RollNo;
            }
            set
            {
                OnRollNoChanging(value);
                ReportPropertyChanging("RollNo");
                _RollNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RollNo");
                OnRollNoChanged();
            }
        }
        private global::System.Int32 _RollNo;
        partial void OnRollNoChanging(global::System.Int32 value);
        partial void OnRollNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Semester
        {
            get
            {
                return _Semester;
            }
            set
            {
                OnSemesterChanging(value);
                ReportPropertyChanging("Semester");
                _Semester = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Semester");
                OnSemesterChanged();
            }
        }
        private global::System.String _Semester;
        partial void OnSemesterChanging(global::System.String value);
        partial void OnSemesterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Shift
        {
            get
            {
                return _Shift;
            }
            set
            {
                OnShiftChanging(value);
                ReportPropertyChanging("Shift");
                _Shift = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Shift");
                OnShiftChanged();
            }
        }
        private global::System.String _Shift;
        partial void OnShiftChanging(global::System.String value);
        partial void OnShiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GendarType
        {
            get
            {
                return _GendarType;
            }
            set
            {
                OnGendarTypeChanging(value);
                ReportPropertyChanging("GendarType");
                _GendarType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GendarType");
                OnGendarTypeChanged();
            }
        }
        private global::System.String _GendarType;
        partial void OnGendarTypeChanging(global::System.String value);
        partial void OnGendarTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateofBirth
        {
            get
            {
                return _DateofBirth;
            }
            set
            {
                OnDateofBirthChanging(value);
                ReportPropertyChanging("DateofBirth");
                _DateofBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateofBirth");
                OnDateofBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateofBirth;
        partial void OnDateofBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateofBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Contact
        {
            get
            {
                return _Contact;
            }
            set
            {
                OnContactChanging(value);
                ReportPropertyChanging("Contact");
                _Contact = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Contact");
                OnContactChanged();
            }
        }
        private Nullable<global::System.Int32> _Contact;
        partial void OnContactChanging(Nullable<global::System.Int32> value);
        partial void OnContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Session
        {
            get
            {
                return _Session;
            }
            set
            {
                OnSessionChanging(value);
                ReportPropertyChanging("Session");
                _Session = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Session");
                OnSessionChanged();
            }
        }
        private global::System.String _Session;
        partial void OnSessionChanging(global::System.String value);
        partial void OnSessionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="MISModel", Name="SP_GRIDVIEWDISPLAYS_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_GRIDVIEWDISPLAYS_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SP_GRIDVIEWDISPLAYS_Result object.
        /// </summary>
        /// <param name="rollNo">Initial value of the RollNo property.</param>
        /// <param name="shift">Initial value of the Shift property.</param>
        public static SP_GRIDVIEWDISPLAYS_Result CreateSP_GRIDVIEWDISPLAYS_Result(global::System.Int32 rollNo, global::System.String shift)
        {
            SP_GRIDVIEWDISPLAYS_Result sP_GRIDVIEWDISPLAYS_Result = new SP_GRIDVIEWDISPLAYS_Result();
            sP_GRIDVIEWDISPLAYS_Result.RollNo = rollNo;
            sP_GRIDVIEWDISPLAYS_Result.Shift = shift;
            return sP_GRIDVIEWDISPLAYS_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RollNo
        {
            get
            {
                return _RollNo;
            }
            set
            {
                OnRollNoChanging(value);
                ReportPropertyChanging("RollNo");
                _RollNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RollNo");
                OnRollNoChanged();
            }
        }
        private global::System.Int32 _RollNo;
        partial void OnRollNoChanging(global::System.Int32 value);
        partial void OnRollNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Semester
        {
            get
            {
                return _Semester;
            }
            set
            {
                OnSemesterChanging(value);
                ReportPropertyChanging("Semester");
                _Semester = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Semester");
                OnSemesterChanged();
            }
        }
        private global::System.String _Semester;
        partial void OnSemesterChanging(global::System.String value);
        partial void OnSemesterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Shift
        {
            get
            {
                return _Shift;
            }
            set
            {
                OnShiftChanging(value);
                ReportPropertyChanging("Shift");
                _Shift = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Shift");
                OnShiftChanged();
            }
        }
        private global::System.String _Shift;
        partial void OnShiftChanging(global::System.String value);
        partial void OnShiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GendarType
        {
            get
            {
                return _GendarType;
            }
            set
            {
                OnGendarTypeChanging(value);
                ReportPropertyChanging("GendarType");
                _GendarType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GendarType");
                OnGendarTypeChanged();
            }
        }
        private global::System.String _GendarType;
        partial void OnGendarTypeChanging(global::System.String value);
        partial void OnGendarTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateofBirth
        {
            get
            {
                return _DateofBirth;
            }
            set
            {
                OnDateofBirthChanging(value);
                ReportPropertyChanging("DateofBirth");
                _DateofBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateofBirth");
                OnDateofBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateofBirth;
        partial void OnDateofBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateofBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Contact
        {
            get
            {
                return _Contact;
            }
            set
            {
                OnContactChanging(value);
                ReportPropertyChanging("Contact");
                _Contact = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Contact");
                OnContactChanged();
            }
        }
        private Nullable<global::System.Int32> _Contact;
        partial void OnContactChanging(Nullable<global::System.Int32> value);
        partial void OnContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Session
        {
            get
            {
                return _Session;
            }
            set
            {
                OnSessionChanging(value);
                ReportPropertyChanging("Session");
                _Session = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Session");
                OnSessionChanged();
            }
        }
        private global::System.String _Session;
        partial void OnSessionChanging(global::System.String value);
        partial void OnSessionChanged();

        #endregion

    }

    #endregion

    
}
